project:
  type: website
  output-dir: "."

website:
  title: ""
  navbar:
    # logo: wedding_title3.png  # Path to your logo file
    pinned: true
    search: false


format:
  html:
    theme: litera
    mainfont: system-ui; 
    highlight-style: atom-one  # atom-one espresso
    css: styles.css
